### ISSUE TITLE
Card abbreviations missing

### ISSUE THREAD

**Issue by tiedyedguy** [icesphere/star-realms-simulator#2]
In your getGameState, you have a few abbreviations which don't align to cards:

ey, sn, co, rs, bb, mc

Some made sense, but bb could be multiple.

**Comment by icesphere** [comment]
Thanks, I'll take a look at those.

**Comment by icesphere** [comment]
I used to have a bunch of two letter abbreviations, but once I added in all of the crisis cards and the colony wars cards, it was too easy to have multiple cards match, so I got rid of most of those, but forgot to update them in getGameState.  It should be fixed now.
