### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by tiedyedguy** [icesphere/star-realms-simulator#3]
I had to take out running with events, it was giving an undefined player error.  I believe it happens when the event is pulled in the first trade row.

I also assume you know this :)

**Comment by icesphere** [comment]
Nope didn't know about that one :)  I haven't run very many simulations with Events.

**Comment by icesphere** [comment]
I ran a bunch of simulations with events, but never saw the error, but I looked at the code and I think I found the cause of the error, so hopefully it is fixed now.
